"""add spam_keyword to spammessages

Revision ID: 00b4fffe6f66
Revises: 850bcec4cf39
Create Date: 2026-08-18 16:47:08.903196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b4fffe6f66'
down_revision: Union[str, Sequence[str], None] = '850bcec4cf39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spam_messages', sa.Column('spam_keyword', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spam_messages', 'spam_keyword')
    # ### end Alembic commands ###
