"""deleted bot tagged message

Revision ID: adf28c56055b
Revises: 71777003a5a0
Create Date: 2026-08-21 12:17:13.988734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf28c56055b'
down_revision: Union[str, Sequence[str], None] = '71777003a5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_tagged_messages_user_id'), table_name='bot_tagged_messages')
    op.drop_table('bot_tagged_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_tagged_messages',
    sa.Column('tagged_bot_username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_message_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_tagged_messages_user_id'), 'bot_tagged_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###
